[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.4.0",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-postgres>=0.0.18",
    "peft>=0.21.2",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "sentence-transformers>=6.1.0",
    "tzdata>=2026.5",
]
